sonar.projectKey=MilySierra_Itsuki-Backend
sonar.sources=src
sonar.java.binaries=target/classes
sonar.exclusions=src/test/**,**/*.js,**/*.ts
sonar.coverage.exclusions=**/entities/**
sonar.organization = milysierra